[versions]
agp = "8.8.0-alpha05"
android-compileSdk = "35"
android-minSdk = "21"
android-targetSdk = "35"

detekt = "1.23.7"
jetbrains-compose = "1.7.3"
kotlin = "2.1.10"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.10.0"
androidx-camera-camera2 = "androidx.camera:camera-camera2:1.4.1"
androidx-camera-lifecycle = "androidx.camera:camera-lifecycle:1.4.1"
androidx-camera-view = "androidx.camera:camera-view:1.4.1"
androidx-concurrent-futures = "androidx.concurrent:concurrent-futures-ktx:1.2.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.7"
androidx-ui-tooling = "androidx.compose.ui:ui-tooling:1.7.8"
androidx-ui-tooling-preview-android = "androidx.compose.ui:ui-tooling-preview-android:1.7.8"

detekt-compose = "io.nlopez.compose.rules:detekt:0.4.22"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

koin-compose = "io.insert-koin:koin-compose:4.0.2"

kotlin-coroutines-swing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.1"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
binary-compatibility = "org.jetbrains.kotlinx.binary-compatibility-validator:0.17.0"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
m2p = { id = "io.github.composegears.m2p" }